### PR TITLE
Beginning of new UI design

### PR DESCRIPTION
**Pull request by fatmali**

### CODE REVIEW

**Comment by fatmali** [comment]
Screen Shot 2019-12-19 at 11 03 05 PM

**Review by miami78 — COMMENTED** [review]
looks good, awesome work!

**Comment by allanyego** [comment]
Looks great from here @fatmali.

**Review by MarvinKweyu — COMMENTED** [review]
The UI is just right :+1:

**Comment by allanyego** [comment]
Have we agreed on testing the front-end? Cause Travis is all up there whining...

**Comment by fatmali** [comment]
Tests run fine, there is nothing in the .travis.yml file thats why

**Comment by fatmali** [comment]
Aside from the looking of the UI, can you review the code as well?

**Pull request merged**
